using System;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

// REFATORAÇÃO: a lógica de desbloquear items nao deveria ser chamada por aqui? ela está em SHopUI
// refatoarção: ajustar cores para refletir melhor os estados 
// REFATORAAR: referencias no unity editor de acordo com o layout necessario.

/// <summary>
/// Represents a compact shop item card showing icon, name, and level.
/// </summary>
public class ShopItemCard : MonoBehaviour, IPointerClickHandler {

    #region SERIALIZED FIELDS

    [Header("UI Elements")]
    [SerializeField] private Image itemIcon;
    [SerializeField] private TextMeshProUGUI itemNameText;
    [SerializeField] private TextMeshProUGUI itemLevelText;

    [Header("Visual States")]
    [SerializeField] private Image cardBackground;
    [SerializeField] private Color lockedColor = new Color(0.5f, 0.5f, 0.5f, 1f);
    [SerializeField] private Color unlockedColor = Color.white;
    [SerializeField] private Color maxLevelColor = new Color(1f, 0.84f, 0f, 1f);

    #endregion

    #region FIELDS

    private ShopItemDataSO currentItemData;
    private Action<ShopItemDataSO> selectionCallback;

    #endregion

    #region METHODS

    /// <summary>
    /// Initializes the card with the given item data, setting up visuals and state based on player progress.
    /// </summary>
    /// <param name="itemData"></param>
    public void Setup(ShopItemDataSO itemData) {
        currentItemData = itemData;
        if (currentItemData == null) return;

        if (itemIcon != null) itemIcon.sprite = currentItemData.Icon;
        if (itemNameText != null) itemNameText.text = currentItemData.ItemName;

        InternalRefreshCardState();
    }

    /// <summary>
    /// Registers callbacks so the parent UI can react to card selection.
    /// </summary>
    /// <param name="onSelected">Callback fired when this card is selected by click.</param>
    public void SetCallbacks(Action<ShopItemDataSO> onSelected) {
        selectionCallback = onSelected;
    }

    /// <summary>
    /// Handles clicks on this card, notifying the parent shop UI about selection.
    /// </summary>
    /// <param name="eventData">Pointer event data generated by Unity's EventSystem.</param>
    public void OnPointerClick(PointerEventData eventData) {
        NotifySelected();
    }

    /// <summary>
    /// Public method to refresh card state from outside (used by ShopUI after upgrades).
    /// </summary>
    public void RefreshCardState() {
        InternalRefreshCardState();
    }

    /// <summary>
    /// Internal method that updates the card's visuals and interactivity based on the current item data and player progress.
    /// This method is called whenever the card needs to refresh its state (e.g., after an unlock or upgrade).
    /// CONCEITO: Use IsItemUnlocked() and GetItemLevel() instead of weapon-specific methods
    /// to ensure all 9 items (weapons, consumables, buildables) display correct state.
    /// </summary>
    private void InternalRefreshCardState() {
        if (currentItemData == null || PlayerProgress.Instance == null) return;

        string itemID = currentItemData.ItemID;
        // CONCEITO: Generic check using IsItemUnlocked() instead of IsWeaponUnlocked()
        // allows this to work for all item types (weapons, consumables, buildables).
        bool isUnlocked = PlayerProgress.Instance.IsItemUnlocked(itemID);
        int currentLevel = PlayerProgress.Instance.GetItemLevel(itemID);
        // CONCEITO: Use dynamic max level from item's ScriptableObject (not hardcoded 10)
        int maxLevel = PlayerProgress.Instance.GetItemMaxLevel(itemID);
        bool isMaxLevel = currentLevel >= maxLevel;

        if (itemLevelText != null) {
            itemLevelText.text = !isUnlocked ? "Locked" : isMaxLevel ? "Maxed Out" : $"Level {currentLevel}";
        }

        if (cardBackground != null) {
            cardBackground.color = !isUnlocked ? lockedColor : isMaxLevel ? maxLevelColor : unlockedColor;
        }
    }

    /// <summary>
    /// Safely notifies the parent UI that this card is the active selection.
    /// </summary>
    private void NotifySelected() {
        selectionCallback?.Invoke(currentItemData);
    }

    #endregion
}
