using System;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

/// <summary>
/// Represents a compact shop item card showing icon, name, and level.
/// Unlock/Upgrade logic is handled by the parent ShopUI, not the card itself.
/// </summary>
public class ShopItemCard : MonoBehaviour, IPointerClickHandler {
    [Header("UI Elements")]
    [SerializeField] private Image itemIcon;
    [SerializeField] private TextMeshProUGUI itemNameText;
    [SerializeField] private TextMeshProUGUI itemLevelText;

    [Header("Button")]
    [SerializeField] private Button unlockUpgradeButton;
    [SerializeField] private TextMeshProUGUI unlockUpgradeButtonText;

    [Header("Visual States")]
    [SerializeField] private Image cardBackground;
    [SerializeField] private Color lockedColor = new Color(0.5f, 0.5f, 0.5f, 1f);
    [SerializeField] private Color unlockedColor = Color.white;
    [SerializeField] private Color maxLevelColor = new Color(1f, 0.84f, 0f, 1f);

    private ShopItemDataSO currentItemData;
    private Action<ShopItemDataSO> selectionCallback;
    private Action<ShopItemDataSO> stateChangedCallback;
    private Action<ShopItemDataSO> onUnlockUpgradeClick;

    private void Awake() {
        if (unlockUpgradeButton != null)
            unlockUpgradeButton.onClick.AddListener(OnUnlockUpgradeClick);
    }

    public void Setup(ShopItemDataSO itemData) {
        currentItemData = itemData;
        if (currentItemData == null) return;

        if (itemIcon != null) itemIcon.sprite = currentItemData.Icon;
        if (itemNameText != null) itemNameText.text = currentItemData.ItemName;
        
        InternalRefreshCardState();
    }

    /// <summary>
    /// Registers callbacks so the parent UI can react to card selection and state changes.
    /// </summary>
    /// <param name="onSelected">Callback fired when this card is selected by click.</param>
    /// <param name="onStateChanged">Callback fired after this card refreshes its state.</param>
    /// <param name="onUnlockUpgrade">Callback fired when the unlock/upgrade button is clicked.</param>
    public void SetCallbacks(Action<ShopItemDataSO> onSelected, Action<ShopItemDataSO> onStateChanged, Action<ShopItemDataSO> onUnlockUpgrade) {
        selectionCallback = onSelected;
        stateChangedCallback = onStateChanged;
        onUnlockUpgradeClick = onUnlockUpgrade;
    }

    /// <summary>
    /// Handles clicks on this card, notifying the parent shop UI about selection.
    /// </summary>
    /// <param name="eventData">Pointer event data generated by Unity's EventSystem.</param>
    public void OnPointerClick(PointerEventData eventData) {
        NotifySelected();
    }

    /// <summary>
    /// Public method to refresh card state from outside (used by ShopUI after upgrades).
    /// </summary>
    public void RefreshCardState() {
        InternalRefreshCardState();
    }

    /// MÉTODO PRINCIPAL: Atualiza o estado visual do card baseado no progresso do jogador
    /// Este método é chamado toda vez que algo muda (compra, upgrade, etc)
    /// CONCEITO: State-based UI - a interface reflete o estado do jogo
    private void InternalRefreshCardState() {
        // EARLY RETURN: Se dados essenciais estão faltando, sai da função imediatamente
        // Isso previne NullReferenceException (erro muito comum em Unity)
        if (currentItemData == null || PlayerProgress.Instance == null) return;

        // CACHE DE VALORES: Armazenamos valores usados múltiplas vezes em variáveis locais
        // Isso evita chamar os mesmos métodos repetidamente (mais eficiente)
        string itemID = currentItemData.ItemID;
        bool isUnlocked = PlayerProgress.Instance.IsWeaponUnlocked(itemID);
        int currentLevel = PlayerProgress.Instance.GetWeaponLevel(itemID);
        bool isMaxLevel = currentLevel >= PlayerProgress.MAX_UPGRADE_LEVEL;

        // ATUALIZAÇÃO DE TEXTO DO NÍVEL
        // OPERADOR TERNÁRIO ANINHADO: condição ? verdadeiro : falso
        // Lê-se: "Se não desbloqueado, mostra LOCKED; senão, se max level, mostra MAX LEVEL; senão, mostra Level X/10"
        if (itemLevelText != null) {
            itemLevelText.text = !isUnlocked ? "LOCKED" : isMaxLevel ? "MAX LEVEL" : $"Level {currentLevel}/{PlayerProgress.MAX_UPGRADE_LEVEL}";
        }

        // FEEDBACK VISUAL: Cor de fundo muda baseado no estado
        // CINZA = locked, BRANCO = unlocked, DOURADO = max level
        if (cardBackground != null) {
            cardBackground.color = !isUnlocked ? lockedColor : isMaxLevel ? maxLevelColor : unlockedColor;
        }

        // BOTÃO UNLOCK/UPGRADE - Lógica de State Machine
        // O botão muda seu comportamento baseado no estado atual
        if (unlockUpgradeButton != null) {
            if (!isUnlocked) {
                // ESTADO 1: LOCKED - Botão mostra "UNLOCK"
                if (unlockUpgradeButtonText != null) unlockUpgradeButtonText.text = "UNLOCK";
                unlockUpgradeButton.interactable = EconomyManager.Instance != null && EconomyManager.Instance.CanAfford(currentItemData.UnlockCost);
            } else if (isMaxLevel) {
                // ESTADO 2: MAX LEVEL - Botão desabilitado
                if (unlockUpgradeButtonText != null) unlockUpgradeButtonText.text = "MAX LEVEL";
                unlockUpgradeButton.interactable = false;
            } else {
                // ESTADO 3: UNLOCKED (1-9) - Botão mostra "UPGRADE"
                int cost = CalculateUpgradeCost(currentLevel);
                if (unlockUpgradeButtonText != null) unlockUpgradeButtonText.text = $"UPGRADE";
                unlockUpgradeButton.interactable = EconomyManager.Instance != null && EconomyManager.Instance.CanAfford(cost);
            }
        }

        // Notify the parent UI so right-side details stay in sync after unlock/upgrade/ammo changes.
        stateChangedCallback?.Invoke(currentItemData);
    }

    private void OnUnlockUpgradeClick() {
        NotifySelected();
        onUnlockUpgradeClick?.Invoke(currentItemData);
    }

    private int CalculateUpgradeCost(int currentLevel) {
        return UpgradeManager.Instance != null ? UpgradeManager.Instance.GetNextUpgradeCost(currentItemData.ItemID, currentItemData.BaseUpgradeCost) : 0;
    }

    /// <summary>
    /// Safely notifies the parent UI that this card is the active selection.
    /// </summary>
    private void NotifySelected() {
        selectionCallback?.Invoke(currentItemData);
    }
}
