using System;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

/// <summary>
/// Represents a compact shop item card showing icon, name, and level.
/// </summary>
public class ShopItemCard : MonoBehaviour, IPointerClickHandler {

    #region SERIALIZED FIELDS

    [Header("UI Elements")]
    [SerializeField] private Image itemIcon;
    [SerializeField] private TextMeshProUGUI itemNameText;
    [SerializeField] private TextMeshProUGUI itemLevelText;

    [Header("State Overlays")]
    [SerializeField] private Image lockedOverlay;
    [SerializeField] private Color lockedOverlayColor = new Color(0.5f, 0.5f, 0.5f, 1f);

    [SerializeField] private Image unlockedBackground;
    [SerializeField] private Color unlockedBackgroundColor = Color.white;

    [SerializeField] private Image maxedBackground;
    [SerializeField] private Color maxedBackgroundColor = new Color(1f, 0.84f, 0f, 1f);

    [Header("Selection Overlay")]
    [SerializeField] private Image selectedOverlay;
    [SerializeField] private Color selectedOverlayColor = new Color(0.3f, 0.8f, 0.3f, 1f);

    #endregion

    #region FIELDS

    private ShopItemDataSO currentItemData;
    private Action<ShopItemDataSO> selectionCallback;
    private bool isSelected;

    #endregion

    #region METHODS

    /// <summary>
    /// Initializes the card with the given item data, setting up visuals and state based on player progress.
    /// </summary>
    /// <param name="itemData"></param>
    public void Setup(ShopItemDataSO itemData) {
        currentItemData = itemData;
        if (currentItemData == null) return;

        if (itemIcon != null) itemIcon.sprite = currentItemData.Icon;
        if (itemNameText != null) itemNameText.text = currentItemData.ItemName;

        InternalRefreshCardState();
    }

    /// <summary>
    /// Registers callbacks so the parent UI can react to card selection.
    /// </summary>
    /// <param name="onSelected">Callback fired when this card is selected by click.</param>
    public void SetCallbacks(Action<ShopItemDataSO> onSelected) {
        selectionCallback = onSelected;
    }

    /// <summary>
    /// Handles clicks on this card, notifying the parent shop UI about selection.
    /// </summary>
    /// <param name="eventData">Pointer event data generated by Unity's EventSystem.</param>
    public void OnPointerClick(PointerEventData eventData) {
        NotifySelected();
    }

    /// <summary>
    /// Public method to refresh card state from outside (used by ShopUI after upgrades).
    /// </summary>
    public void RefreshCardState() {
        InternalRefreshCardState();
    }

    /// <summary>
    /// Internal method that updates the card's visuals based on item data and player progress.
    /// Uses IsItemUnlocked() and GetItemLevel() for consistent state display across all item types.
    /// </summary>
    private void InternalRefreshCardState() {
        if (currentItemData == null || PlayerProgress.Instance == null) return;

        string itemID = currentItemData.ItemID;
        bool isUnlocked = PlayerProgress.Instance.IsItemUnlocked(itemID);
        int currentLevel = PlayerProgress.Instance.GetItemLevel(itemID);
        int maxLevel = PlayerProgress.Instance.GetItemMaxLevel(itemID);
        bool isMaxLevel = currentLevel >= maxLevel;

        if (itemLevelText != null) {
            itemLevelText.text = !isUnlocked ? "Locked" : isMaxLevel ? "Maxed Out" : $"Level {currentLevel}";
        }

        RefreshOverlaysState();
    }

    /// <summary>
    /// Sets the selected state of this card.
    /// </summary>
    public void SetSelected(bool selected) {
        isSelected = selected;
        RefreshOverlaysState();
    }

    /// <summary>
    /// Refreshes overlay images based on item state. Hides all overlays first, then shows the appropriate one.
    /// </summary>
    private void RefreshOverlaysState() {
        if (currentItemData == null || PlayerProgress.Instance == null) return;

        string itemID = currentItemData.ItemID;
        bool isUnlocked = PlayerProgress.Instance.IsItemUnlocked(itemID);
        int currentLevel = PlayerProgress.Instance.GetItemLevel(itemID);
        int maxLevel = PlayerProgress.Instance.GetItemMaxLevel(itemID);
        bool isMaxLevel = currentLevel >= maxLevel;

        SetOverlayActive(lockedOverlay, false);
        SetOverlayActive(unlockedBackground, false);
        SetOverlayActive(maxedBackground, false);

        if (!isUnlocked) {
            ApplyVisualState(lockedOverlay, lockedOverlayColor);
        }
        else if (isMaxLevel) {
            ApplyVisualState(maxedBackground, maxedBackgroundColor);
        }
        else {
            ApplyVisualState(unlockedBackground, unlockedBackgroundColor);
        }

        if (isSelected) {
            ApplyVisualState(selectedOverlay, selectedOverlayColor);
        }
        else {
            SetOverlayActive(selectedOverlay, false);
        }
    }

    /// <summary>
    /// Activates an overlay and applies its color.
    /// </summary>
    private void ApplyVisualState(Image overlay, Color color) {
        if (overlay == null) return;

        overlay.gameObject.SetActive(true);
        overlay.color = color;
    }

    /// <summary>
    /// Deactivates an overlay and optionally resets its color.
    /// </summary>
    private void SetOverlayActive(Image overlay, bool active, bool resetColor = false) {
        if (overlay == null) return;

        overlay.gameObject.SetActive(active);

        if (!active && resetColor) {
            overlay.color = Color.white;
        }
    }

    /// <summary>
    /// Safely notifies the parent UI that this card is the active selection.
    /// </summary>
    private void NotifySelected() {
        selectionCallback?.Invoke(currentItemData);
    }

    #endregion
}
