name: Discord Notify

on:
  push:
    branches: [master, main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d @- $DISCORD_WEBHOOK << EOF
          {
            "username": "GitHub - Deadzone",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [
              {
                "title": "Novo Commit",
                "url": "${{ github.event.head_commit.url }}",
                "color": 5814782,
                "fields": [
                  {
                    "name": "Repositório",
                    "value": "`${{ github.repository }}`",
                    "inline": true
                  },
                  {
                    "name": "Branch",
                    "value": "`${{ github.ref_name }}`",
                    "inline": true
                  },
                  {
                    "name": "Autor",
                    "value": "${{ github.actor }}",
                    "inline": true
                  },
                  {
                    "name": "Mensagem",
                    "value": "${{ github.event.head_commit.message }}"
                  }
                ],
                "footer": {
                  "text": "GitHub Actions"
                }
              }
            ]
          }
          EOF